### ISSUE TITLE
Fejléc top

### ISSUE THREAD

**Issue by kelna** [kelna/lakoauto#14]
Fejlec Top:

- az ikonok nincsenek középen, picit túl nagyok  és a fekete túl sok oda próbáljuk meg ezzel: 212121, vagy a fejlécben lévő mousover nelküli textnek a szinével.
- az iknok között hiányzik az elvállasztó bar
- a méretük kb akkora kéne legyen hogy annyi legyen a hosszuk, mint a amilakoautonk textnek annal az a betü túl nagy - de azt hátha cseréljük

**Comment by Sanyos** [comment]
az iknok között hiányzik az elvállasztó bar - nem lesz mer csúf
többi fixed
