### ISSUE TITLE
Aláhúzás túlnyúlik

### ISSUE THREAD

**Issue by kelna** [kelna/lakoauto#2]
A Home gomb alatt az aláhúzás túlnyúlik, ha kicsit balra mozdul a kurzor. Fixen kéne maradnia a Home alatt.

**Comment by Sanyos** [comment]
Csináltál vele valamit vagy megjavult magától?

**Comment by kelna** [comment]
LOL, nem nyúltam hozzá. Na ezt szeretem. :)
