### ISSUE TITLE
Fehér sáv jobb oldalon

### ISSUE THREAD

**Issue by kelna** [kelna/lakoauto#27]

**Comment by kelna** [comment]
Javítottam a `body`-hoz az `overflow-x:hidden` sort hozzáadva. Azért ez nem oldja meg a problémát, csak elegánsan a szőnyeg alá sepri. Jó lenne kideríteni, hogy mi a valódi hiba, de addig jóvanezígy.

**Comment by kelna** [comment]
Hasonló lehet a hiba az oldal alján is, ami 4px-lel nyúlik túl. De az `overflow-y:hidden` hatására rossz dolgok történnek, úgyhogy ezt máshogy kell fixelni.

**Comment by Sanyos** [comment]
Az alsó részre van külön issue

**Comment by kelna** [comment]
Ez valahol útközben megoldódott. Jó lenne tudni, hogy mitől, de zárom.
