### ISSUE TITLE
Header alatt látszik a lap

### ISSUE THREAD

**Issue by kelna** [kelna/lakoauto#3]
Mikor legörgetsz, a header helyén az áttűnés ideje alatt átlátszik a lap az "ismerje meg" felirattal. Úgy kéne megoldani, hogy a header fehér sávja fixen rögzítve legyen a menühöz, és csak az ikonok ússzanak be egy divben.

**Comment by Sanyos** [comment]
Az egész fehér sávot el kell tűntetni görgetésnél. Majd megoldom hogy ne késsen van rá 1 ötletem.

**Comment by Sanyos** [comment]
fixed
