### ISSUE TITLE
A footert nem látom

### ISSUE THREAD

**Issue by Sanyos** [kelna/lakoauto#7]

**Comment by kelna** [comment]
Hiába állítom be a hátteret a footerben, nem látszódik. A map cseszi el valahogy, de nem tudom, hogy.

**Comment by kelna** [comment]
Javítva. A float:left csesztve el a hátteret. Helyette display:inline-blockkal oldottam meg. Azt meg **nem a wrapperbe kell írni**, hanem minden olyan divbe, amit egymás mellé akarunk igazítani.
